// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhDRwbmckMF1oO19dUcFL7Vy0jaWT6F8',
    appId: '1:1041371466897:web:d531eb97ef0ae39e81c330',
    messagingSenderId: '1041371466897',
    projectId: 'healthcare-cf639',
    authDomain: 'healthcare-cf639.firebaseapp.com',
    storageBucket: 'healthcare-cf639.firebasestorage.app',
    measurementId: 'G-JGB1SJSYJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnoe07UmBZPbMuPh15sorXR75egbyTmw',
    appId: '1:1041371466897:android:3df83152706fb32981c330',
    messagingSenderId: '1041371466897',
    projectId: 'healthcare-cf639',
    storageBucket: 'healthcare-cf639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArumt6vvDxZVFNKhfT6naNwykS_m8ZCRw',
    appId: '1:1041371466897:ios:61cc2d2f67ee936881c330',
    messagingSenderId: '1041371466897',
    projectId: 'healthcare-cf639',
    storageBucket: 'healthcare-cf639.firebasestorage.app',
    iosClientId: '1041371466897-b9in50s4dgrrbdm7apjmtt501fr2b966.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcare',
  );
}
